# Generated by Django 4.0.5 on 2022-07-25 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('libro', '0004_remove_autor_estado_remove_autor_fecha_creacion_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='libro',
            name='autor_id',
        ),
    ]
